services:
  mindfactory-nginx:
    image: ghcr.io/412228-rinaudo/mindfactory-frontend:1.0
    ports:
      - "3000:80"
    restart: unless-stopped
    container_name: mindfactory-frontend
  mindfactory-backend:
    image: ghcr.io/412228-rinaudo/mindfactory-backend:1.0
    container_name: mindfactory-backend
    restart: unless-stopped
    depends_on:
      - mindfactory-db
    environment:
      NODE_ENV: development
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      HOST: mindfactory-db
      DATABASE_PORT: 5432
      DATABASE_NAME: mindfactory-db
      PORT: 8000
      JWT_EXPIRES_IN: 24h
      JWT_SECRET: N6zQ8Xr+M9cF4kYkqKx7b8ZKkN3nKpP0b8+Qk8yVZlU=
      DATABASE_URL: postgresql://postgres:postgres@mindfactory-db:5432/mindfactory-db?schema=public
    ports:
      - "8000:8000"
  mindfactory-db:
    image: postgres:16-alpine
    container_name: mindfactory-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mindfactory-db
    ports:
      - "5432:5432"
    volumes:
      - mindfactory-db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  mindfactory-db-data:
    name: mindfactory-db-data 
